### ISSUE TITLE
JNI Error

### ISSUE THREAD

**Issue by ExplodinGG** [Mojang/slicer#17]
Whenever I try and convert my resource pack with 1.1.3-SNAPSHOT or 1.1.5-SNAPSHOT I get the message:

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/mojang/slicer/Main has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:621)
	
I am using Arch Linux and have later than Java 17 installed (Java 21, 22 and 17) I downloaded several versions of java to see if it would still work but it didn't

**Comment by satanicantichrist** [comment]
Do you have any older version of java installed? 
Try to run `java -version` to verify that you are actually using java 17

**Comment by slicedlime** [comment]
You are running the application with java 8. Keep in mind that the `java` alias on your system may be a different default than the latest version.
